### ISSUE TITLE
Option to disable cursorline timeout completely

### ISSUE THREAD

**Issue by axieax** [yamatsum/nvim-cursorline#12]
Hello, it seems that the cursorline keeps flashing everytime it is updated (if vim.g.cursorline_timeout is set to 0). This seems to be due to the timer updating the cursorline to the same colour.

**Comment by axieax** [comment]
I've found a way to disable this timer update if the cursorline_timeout is set to 0 (indicating disabled feature). This results in a smoother experience. However, I just found out that my changes cause unexpected behaviour, such as cursorline in Telescope query fields. Could you see if you can fix this as well before merging?

**Comment by tristone13th** [comment]
The same problem too.

**Comment by axieax** [comment]
@tristone13th i'm using [vim-brightest](https://github.com/osyo-manga/vim-brightest) with `vim.g["brightest#highlight"] = { group = "BrightestUnderline" }` instead and it works flawlessly :D

**Comment by tristone13th** [comment]
> @tristone13th i'm using [vim-brightest](https://github.com/osyo-manga/vim-brightest) with `vim.g["brightest#highlight"] = { group = "BrightestUnderline" }` instead and it works flawlessly :D

Thanks! it seems that itchyny/vim-cursorword doesn't have this issue too, you can have a try.

**Comment by axieax** [comment]
I think I've tried that a while ago but it doesn't play nice with my highlight groups, so I've stuck to vim-brightest ever since :))
