### ISSUE TITLE
Breaks highlighting on campsiers/snap

### ISSUE THREAD

**Issue by rawhat** [yamatsum/nvim-cursorline#14]
Making this because I have determined with my setup that disabling this plugin fixes the issue.  Not sure if there are some additional factors with my setup that are causing this.  But I can at least confirm that commenting out this section of the config fixes the problem.

To confirm... without this plugin, I see:

![image](https://user-images.githubusercontent.com/2095509/136311163-a39224f2-4e6e-4401-80bd-4b13e36b3b7e.png)

With this plugin, I see:

![image](https://user-images.githubusercontent.com/2095509/136311313-152b604d-6dcf-4dde-bbf9-d620319ffd0a.png)

Note that the "highlighted" background for the "current item" disappears with this plugin.

This is `camspiers/snap`, setup basically with the default `find_files` setup.  I'm using the `nightfox` theme.

Happy to provide whatever other information is helpful!

**Comment by yamatsum** [comment]
The color of the cursor line of this plugin is highlighted based on `CursorLine`.
Try to change the color with the following settings
```
vim.cmd("hi CursorLine guibg=#ffffff")
```

**Comment by yamatsum** [comment]
@rawhat 
Have you solved the problem yet?
If it is resolved, please close it.

**Comment by rawhat** [comment]
I don't use that plugin anymore, and this works just fine with telescope.  It looks like there is an open issue regarding some highlighting in the issues for that plugin.  I will close this for now, as I don't think it's related to cursorline!  Sorry for the delay.
