### ISSUE TITLE
Your plugin break anything about colorscheme, I removed it.

### ISSUE THREAD

**Issue by nyngwang** [yamatsum/nvim-cursorline#15]
I just removed your plugin and then everything go back to normal.

Question link: https://vi.stackexchange.com/questions/34747/cursorline-became-black-when-cursor-is-moving?noredirect=1#comment62834_34747

---

If I change the colorscheme by `<option>`+`12345`

```
:colorscheme newsprint
```
Then when I will firstly got the expected result:

<img src="https://i.stack.imgur.com/UE1rg.png" width="500">

But then if I move my cursor by `j`/`k`, it shows some ugly bull-sh_t and the clean cursorline gone:

<img src="https://i.stack.imgur.com/hPxBw.png" width="500">

I can give you bounty if you know how to fix this. This has caused me so much time.

---

The version I'm using:
```
NVIM v0.6.0-dev+452-gb3e0d6708
Build type: Release
LuaJIT 2.1.0-beta3
```

**Comment by yamatsum** [comment]
The color of the cursor line of this plugin is highlighted based on `CursorLine`.
Try to change the color with the following settings
```
vim.cmd("hi CursorLine guibg=#ffffff")
```

**Comment by yamatsum** [comment]
@nyngwang 
Have you solved the problem yet?
If it is resolved, please close it.

**Comment by nyngwang** [comment]
@yamatsum Let me retry it again now.

**Comment by nyngwang** [comment]
People have the same issue should use this one instead: https://github.com/xiyaowong/nvim-cursorword
