### ISSUE TITLE
Add the ability to configure highlighting

### ISSUE THREAD

**Issue by Shatur95** [yamatsum/nvim-cursorline#2]
Thank you for the plugin, looks awesome. Could you add the ability to customize highlighting? Like in [vim-cursorword](https://github.com/itchyny/vim-cursorword/blob/master/doc/cursorword.txt#L61).

**Comment by yamatsum** [comment]
i'll do that when i have some time, otherwise, you can submit a PR.

**Comment by Shatur95** [comment]
@yamatsum, I sent a PR, can you check it out?
