### ISSUE TITLE
In nvim version 0.7.0 the function is invalid

### ISSUE THREAD

**Issue by SunJun8** [yamatsum/nvim-cursorline#20]
Default configuration underscore not working

**Comment by yamatsum** [comment]
Thank you for the report! Can you tell me a little more?

**Comment by SunJun8** [comment]
i using packer
```
use { 
  'yamatsum/nvim-cursorline',
  config = function()
    require('nvim-cursorline').setup()
  end
}
```
When I upgraded nvim to 0.7.0, underscore didn't work

**Comment by SunJun8** [comment]
fxxx, it works again now
