### ISSUE TITLE
how to add these in init.vim

### ISSUE THREAD

**Issue by Aneeqasif** [yamatsum/nvim-cursorline#21]
how can i add the setup line in init.vim file ? like i dont use paker etc i just use vim plug and add vim configuration code in init.vim , the code given looks like its supposed to be lua .. little noob here plz help

**Comment by silentjay** [comment]
- Add plugin to init.vim "Plug 'gituser/plug-name'"
    - :source $MYVIMRC
    - :PlugClean
    - :PlugInstall

**Comment by Aneeqasif** [comment]
> - :PlugInstall

yeah i have done this but how can i add this

`require('nvim-cursorline').setup {
  cursorline = {
    enable = true,
    timeout = 1000,
    number = false,
  },
  cursorword = {
    enable = true,
    min_length = 3,
    hl = { underline = true },
  }
}`

**Comment by SushritPasupuleti** [comment]
> > * :PlugInstall
> 
> yeah i have done this but how can i add this
> 
> `require('nvim-cursorline').setup { cursorline = { enable = true, timeout = 1000, number = false, }, cursorword = { enable = true, min_length = 3, hl = { underline = true }, } }`

Same issue here!

**Comment by yamatsum** [comment]
If the plugin is loaded, it should work with the following settings. I just recommend using lua

init.vim
```
lua << EOF
require("nvim-cursorline").setup()
EOF
```
