### ISSUE TITLE
Seems to clash with highlight on yank

### ISSUE THREAD

**Issue by cideM** [yamatsum/nvim-cursorline#7]
Whenever I activate this plugin I lose highlight on yank. I'm not doing anything special, I just have this in my `init.vim`

```
  augroup highlight_yank
      autocmd!
      autocmd TextYankPost * silent! lua require'vim.highlight'.on_yank()
  augroup END
```

**Comment by yamatsum** [comment]
What does it mean to lose highlights?

**Comment by cideM** [comment]
Sorry I should have made this a bit more clear. Highlight on yank no longer works at all. I can yank as much as I want but my yank highlighting never appears.

**Comment by yamatsum** [comment]
I also tried and it was highlighted successfully
```
vim.cmd [[au TextYankPost * silent! lua vim.highlight.on_yank()]]
```

**Comment by yamatsum** [comment]
@cideM 
Have you solved the problem yet?
If it is resolved, please close it.

**Comment by cideM** [comment]
I no longer use this and I'll just assume it's working. Sorry for not following up on this.
